### ISSUE TITLE
DeepLX doesn't work

### ISSUE THREAD

**Issue by dddff3445** [dmMaze/BallonsTranslator#542]
When trying to use the DeepLX Api this error appears:

ConnectionError: HTTPSConnectionPool(host='dpltrnslt.bropinesd.online', port=443): Max retries exceeded with url: /translate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DC4F7221A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by bropines** [comment]
> When trying to use the DeepLX Api this error appears:
> 
> ConnectionError: HTTPSConnectionPool(host='dpltrnslt.bropinesd.online', port=443): Max retries exceeded with url: /translate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DC4F7221A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

well yeah my server did not pull dozens of users using the translator at the same time. The problem is that I didn't warn anyone anywhere. @dmMaze , could you attach [this](https://github.com/bropines/Deeplx-vercel?tab=readme-ov-file#for-ballon-translator-users) guide somewhere in the readme in English and Chinese? Thanks

And well, the answer to your question. Here is the link, set up your server here if necessary for China and tencent here is the link to [it](https://github.com/LegendLeo/deeplx-serverless)

**Comment by bropines** [comment]
if you have any questions or difficulties, write here. I do not yet have the Financial And technical ability to maintain a server for many clients without being banned by deepl

**Comment by bropines** [comment]
@dmMaze it seems like this issue can already be closed.
