### ISSUE TITLE
Deleting selected blocks when clicking on `delete`

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#72]
Select the blocks (ctrl + click on the block) and when you click on `delete`, everything is deleted. 
You can also add copying of selected blocks with ctrl + v, but I have already suggested this.

**Comment by dmMaze** [comment]
Deleting multiple selected text blocks had already been implemented.

**Comment by bropines** [comment]
> Deleting multiple selected text blocks had already been implemented.

Multiple deletion yes. But the essence of this issue is to bind the delete to the delete button on the keyboard

**Comment by dmMaze** [comment]
I misunderstood. 
Just implemented it.

**Comment by dmMaze** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/51270320/210074645-27fbd96a-1991-4101-9ee2-8674113d51b3.png">

Copy/paste selected text blocks via right-click menu (or Ctrl+C/Ctrl+V) is supported now.
Please notice when perform paste there should be no text blocks selected on the scene if the desired behavior is to paste text blocks, otherwise text in clipboard will be paste to these selected blocks as required by #69
